FROM jetty

COPY ./WEB-INF /var/lib/jetty/webapps/sink_agent/WEB-INF
COPY ./META-INF /var/lib/jetty/webapps/sink_agent/META-INF

EXPOSE 8080


#COPYRIGHT Fujitsu Limited 2017 and FUJITSU LABORATORIES LTD. 2017